import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiRequest } from '../src/api';
import { getAccessToken } from '../src/auth';

type Item={code:string;prompt:string;min:number;max:number};type Start={session_id:string;instrument_code:string;instrument_version:string;items:Item[]};type Result={normalized_score:number;classification:string;disclaimer:string};
export default function AssessmentDemo(){const [session,setSession]=useState<Start|null>(null);const [answers,setAnswers]=useState<Record<string,number>>({});const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{(async()=>{try{const token=await getAccessToken();setSession(await apiRequest<Start>('/assessments/start',{method:'POST',body:JSON.stringify({instrument_code:'DEMO_WELLBEING'})},token));}catch(e){setError(e instanceof Error?e.message:'Não foi possível iniciar.')}finally{setLoading(false)}})()},[]);
async function submit(){if(!session)return;if(session.items.some(i=>answers[i.code]===undefined)){setError('Responda todos os itens antes de continuar.');return}setLoading(true);setError('');try{const token=await getAccessToken();const r=await apiRequest<Result>(`/assessments/${session.session_id}/submit`,{method:'POST',body:JSON.stringify({answers:session.items.map(i=>({item_code:i.code,numeric_value:answers[i.code]}))})},token);setResult(r);}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setLoading(false)}}
if(result)return <View style={s.result}><Text style={s.kicker}>RESULTADO</Text><Text style={s.score}>{result.normalized_score}</Text><Text style={s.title}>{result.classification}</Text><Text style={s.sub}>{result.disclaimer}</Text><Pressable style={s.primary} onPress={()=>router.replace('/dashboard')}><Text style={s.primaryText}>Ver meu painel</Text></Pressable></View>;
return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>MAPA INICIAL</Text><Text style={s.title}>Check de bem-estar</Text><Text style={s.sub}>Instrumento interno de demonstração para validar a experiência do MVP. Não é um teste diagnóstico.</Text>{loading&&!session&&<ActivityIndicator/>}{session?.items.map(item=><View key={item.code} style={s.card}><Text style={s.question}>{item.prompt}</Text><View style={s.options}>{Array.from({length:item.max-item.min+1},(_,k)=>k+item.min).map(n=><Pressable key={n} style={[s.option,answers[item.code]===n&&s.selected]} onPress={()=>setAnswers(a=>({...a,[item.code]:n}))}><Text style={[s.optionText,answers[item.code]===n&&s.selectedText]}>{n}</Text></Pressable>)}</View></View>)}{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.primary} disabled={loading} onPress={submit}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Concluir avaliação</Text>}</Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:24,paddingTop:62,paddingBottom:40},result:{flex:1,backgroundColor:'#fff',padding:28,justifyContent:'center',alignItems:'center'},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:'#5B5CE2'},title:{fontSize:30,fontWeight:'800',color:'#101828',marginTop:8,textAlign:'center'},sub:{fontSize:15,lineHeight:22,color:'#667085',marginTop:10,marginBottom:22,textAlign:'center'},card:{paddingVertical:22,borderBottomWidth:1,borderBottomColor:'#F2F4F7'},question:{fontSize:17,fontWeight:'700',color:'#101828',lineHeight:24},options:{flexDirection:'row',gap:10,marginTop:16},option:{width:48,height:48,borderRadius:24,backgroundColor:'#F2F4F7',alignItems:'center',justifyContent:'center'},selected:{backgroundColor:'#5B5CE2'},optionText:{fontWeight:'800',color:'#344054'},selectedText:{color:'#fff'},primary:{backgroundColor:'#5B5CE2',padding:17,borderRadius:16,alignItems:'center',marginTop:28,width:'100%'},primaryText:{color:'#fff',fontWeight:'800'},error:{color:'#B42318',marginTop:16},score:{fontSize:72,fontWeight:'800',color:'#5B5CE2',marginTop:14}});