import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { apiRequest, ApiError } from '../src/api';
import { getAccessToken } from '../src/auth';

type MetricKey = 'mood'|'anxiety'|'energy'|'stress'|'sleep_quality';
type Checkin = { id:string; checkin_date:string; mood:number; anxiety:number; energy:number; stress:number; sleep_quality:number; note:string|null; source:string };
const labels: Record<MetricKey,string> = {mood:'Humor', anxiety:'Ansiedade percebida', energy:'Energia', stress:'Estresse percebido', sleep_quality:'Qualidade do sono'};
const keys = Object.keys(labels) as MetricKey[];

export default function Checkin(){
  const [values,setValues]=useState<Record<MetricKey,number>>({mood:5,anxiety:5,energy:5,stress:5,sleep_quality:5});
  const [note,setNote]=useState(''); const [exists,setExists]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const token=await getAccessToken();const current=await apiRequest<Checkin|null>('/checkins/today',{},token);if(current){setExists(true);setValues({mood:current.mood,anxiety:current.anxiety,energy:current.energy,stress:current.stress,sleep_quality:current.sleep_quality});setNote(current.note??'');}}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o check-in.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  async function save(){setSaving(true);setError('');try{const token=await getAccessToken();const body=JSON.stringify({...values,note:note.trim()||null});await apiRequest(exists?'/checkins/today':'/checkins/today',{method:exists?'PUT':'POST',body},token);router.replace('/dashboard');}catch(e){if(e instanceof ApiError&&e.status===409){setExists(true);setError('Já existe um check-in hoje. Atualize e salve novamente.');}else setError(e instanceof Error?e.message:'Não foi possível salvar o check-in.');}finally{setSaving(false);}}
  if(loading)return <View style={s.center}><ActivityIndicator size="large"/><Text style={s.sub}>Carregando check-in…</Text></View>;
  return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.kicker}>CHECK-IN DIÁRIO</Text><Text style={s.title}>{exists?'Atualize seu dia':'Como foi seu dia?'}</Text><Text style={s.sub}>Registre sua percepção de hoje em uma escala de 0 a 10.</Text>{keys.map(key=><View key={key} style={s.metric}><Text style={s.label}>{labels[key]}</Text><View style={s.options}>{[0,2,4,6,8,10].map(n=><Pressable key={n} onPress={()=>setValues(v=>({...v,[key]:n}))} style={[s.option,values[key]===n&&s.optionSelected]}><Text style={[s.optionText,values[key]===n&&s.optionTextSelected]}>{n}</Text></Pressable>)}</View></View>)}<Text style={s.label}>Observação opcional</Text><TextInput style={s.note} multiline value={note} onChangeText={setNote} placeholder="Algo importante sobre hoje?" maxLength={1000}/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={[s.primary,saving&&s.disabled]} disabled={saving} onPress={save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{exists?'Atualizar check-in':'Salvar check-in'}</Text>}</Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:24,paddingTop:62,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10,backgroundColor:'#fff'},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:'#5B5CE2'},title:{fontSize:30,fontWeight:'800',color:'#101828',marginTop:8},sub:{fontSize:15,lineHeight:22,color:'#667085',marginTop:8,marginBottom:22},metric:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:'#F2F4F7'},label:{fontSize:16,fontWeight:'700',color:'#101828',marginBottom:14,marginTop:16},options:{flexDirection:'row',justifyContent:'space-between'},option:{width:44,height:44,borderRadius:22,backgroundColor:'#F2F4F7',alignItems:'center',justifyContent:'center'},optionSelected:{backgroundColor:'#5B5CE2'},optionText:{fontWeight:'700',color:'#344054'},optionTextSelected:{color:'#fff'},note:{minHeight:110,borderWidth:1,borderColor:'#E4E7EC',borderRadius:16,padding:14,textAlignVertical:'top',fontSize:15},primary:{backgroundColor:'#5B5CE2',padding:17,borderRadius:16,alignItems:'center',marginTop:28},disabled:{opacity:.65},primaryText:{color:'#fff',fontWeight:'800'},error:{color:'#B42318',marginTop:16}});