import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { apiRequest } from '../src/api';
import { getAccessToken } from '../src/auth';

type Entry={id:string;title:string|null;content:string;mood_label:string|null};
const moods=['calmo','animado','cansado','sobrecarregado'];

export default function Journal(){
  const [entries,setEntries]=useState<Entry[]>([]);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [mood,setMood]=useState<string|null>(null);const [editingId,setEditingId]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const token=await getAccessToken();setEntries(await apiRequest<Entry[]>('/journal?limit=30',{},token));}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar seus registros.')}finally{setLoading(false)}},[]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  function reset(){setTitle('');setContent('');setMood(null);setEditingId(null)}
  async function save(){if(!content.trim()){setError('Escreva algo antes de salvar.');return}setSaving(true);setError('');try{const token=await getAccessToken();const body=JSON.stringify({title:title.trim()||null,content:content.trim(),mood_label:mood});if(editingId){await apiRequest(`/journal/${editingId}`,{method:'PUT',body},token)}else{await apiRequest('/journal',{method:'POST',body},token)}reset();await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o registro.')}finally{setSaving(false)}}
  function edit(entry:Entry){setEditingId(entry.id);setTitle(entry.title??'');setContent(entry.content);setMood(entry.mood_label)}
  function remove(entry:Entry){Alert.alert('Excluir registro?','Essa ação não pode ser desfeita.',[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:async()=>{try{const token=await getAccessToken();await apiRequest(`/journal/${entry.id}`,{method:'DELETE'},token);if(editingId===entry.id)reset();await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.') }}}])}
  return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.kicker}>DIÁRIO</Text><Text style={s.title}>O que passou pela sua cabeça hoje?</Text><Text style={s.sub}>Este espaço é privado. Registre livremente para acompanhar padrões ao longo do tempo.</Text><TextInput style={s.titleInput} value={title} onChangeText={setTitle} placeholder="Título opcional"/><TextInput style={s.textArea} value={content} onChangeText={setContent} placeholder="Comece a escrever..." multiline textAlignVertical="top"/><View style={s.chips}>{moods.map(x=><Pressable key={x} style={[s.chip,mood===x&&s.chipSelected]} onPress={()=>setMood(mood===x?null:x)}><Text style={[s.chipText,mood===x&&s.chipTextSelected]}>{x}</Text></Pressable>)}</View>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.primary} disabled={saving} onPress={save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{editingId?'Atualizar registro':'Salvar registro'}</Text>}</Pressable>{editingId&&<Pressable style={s.cancel} onPress={reset}><Text style={s.cancelText}>Cancelar edição</Text></Pressable>}<Text style={s.section}>Registros recentes</Text>{loading?<ActivityIndicator/>:entries.length===0?<Text style={s.empty}>Nenhum registro ainda.</Text>:entries.map(e=><View key={e.id} style={s.entry}><View style={s.entryHeader}><Text style={s.entryTitle}>{e.title||'Sem título'}</Text>{e.mood_label&&<Text style={s.mood}>{e.mood_label}</Text>}</View><Text style={s.entryText} numberOfLines={4}>{e.content}</Text><View style={s.actions}><Pressable onPress={()=>edit(e)}><Text style={s.edit}>Editar</Text></Pressable><Pressable onPress={()=>remove(e)}><Text style={s.delete}>Excluir</Text></Pressable></View></View>)}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:24,paddingTop:62,paddingBottom:44},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:'#5B5CE2'},title:{fontSize:30,fontWeight:'800',color:'#101828',marginTop:8},sub:{fontSize:15,lineHeight:22,color:'#667085',marginTop:8,marginBottom:24},titleInput:{borderWidth:1,borderColor:'#E4E7EC',borderRadius:16,padding:15,fontSize:16,marginBottom:12},textArea:{height:220,borderWidth:1,borderColor:'#E4E7EC',borderRadius:18,padding:16,fontSize:16},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:16},chip:{backgroundColor:'#F2F4F7',paddingVertical:9,paddingHorizontal:12,borderRadius:20},chipSelected:{backgroundColor:'#5B5CE2'},chipText:{color:'#475467',fontSize:13,fontWeight:'700'},chipTextSelected:{color:'#fff'},primary:{backgroundColor:'#111827',padding:17,borderRadius:16,alignItems:'center',marginTop:26},primaryText:{color:'#fff',fontWeight:'800'},cancel:{padding:14,alignItems:'center'},cancelText:{color:'#667085',fontWeight:'700'},error:{color:'#B42318',marginTop:14},section:{fontSize:20,fontWeight:'800',color:'#101828',marginTop:34,marginBottom:12},empty:{color:'#98A2B3'},entry:{backgroundColor:'#F8FAFC',borderRadius:18,padding:18,marginBottom:12},entryHeader:{flexDirection:'row',justifyContent:'space-between',gap:10},entryTitle:{fontSize:16,fontWeight:'800',color:'#101828',flex:1},mood:{fontSize:12,fontWeight:'800',color:'#5B5CE2'},entryText:{fontSize:14,lineHeight:20,color:'#667085',marginTop:8},actions:{flexDirection:'row',gap:20,marginTop:14},edit:{fontWeight:'800',color:'#5B5CE2'},delete:{fontWeight:'800',color:'#B42318'}});