import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiRequest } from '../src/api';
import { getAccessToken, logout } from '../src/auth';

type ProfileData={full_name:string|null;birth_date:string|null;gender:string|null;timezone:string;primary_goal:string|null;onboarding_completed:boolean;consent_version:string|null;consented_at:string|null};
type Me={id:string;email:string;is_active:boolean};

export default function Profile(){const [profile,setProfile]=useState<ProfileData|null>(null);const [me,setMe]=useState<Me|null>(null);const [name,setName]=useState('');const [birth,setBirth]=useState('');const [goal,setGoal]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
const load=useCallback(async()=>{setLoading(true);setError('');try{const token=await getAccessToken();const [p,u]=await Promise.all([apiRequest<ProfileData>('/profile',{},token),apiRequest<Me>('/auth/me',{},token)]);setProfile(p);setMe(u);setName(p.full_name??'');setBirth(p.birth_date??'');setGoal(p.primary_goal??'');}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar seu perfil.')}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
async function save(){setSaving(true);setError('');try{const token=await getAccessToken();const updated=await apiRequest<ProfileData>('/profile',{method:'PATCH',body:JSON.stringify({full_name:name.trim()||null,birth_date:birth.trim()||null,primary_goal:goal.trim()||null})},token);setProfile(updated);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
async function signOut(){await logout();router.replace('/login')}
if(loading&&!profile)return <View style={s.center}><ActivityIndicator/><Text style={s.value}>Carregando perfil…</Text></View>;
return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>PERFIL</Text><Text style={s.title}>Sua conta</Text><View style={s.card}><Text style={s.name}>{profile?.full_name||'Usuário VitaPoint'}</Text><Text style={s.email}>{me?.email??''}</Text></View><View style={s.card}><Text style={s.section}>Dados pessoais</Text><Text style={s.label}>Nome</Text><TextInput style={s.input} value={name} onChangeText={setName}/><Text style={s.label}>Data de nascimento</Text><TextInput style={s.input} value={birth} onChangeText={setBirth} placeholder="AAAA-MM-DD"/><Text style={s.label}>Objetivo principal</Text><TextInput style={s.input} value={goal} onChangeText={setGoal}/><Text style={s.value}>Consentimento registrado: {profile?.consent_version??'—'}</Text><Pressable style={s.primary} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Salvar alterações</Text>}</Pressable></View>{!!error&&<Text style={s.error}>{error}</Text>}<View style={s.card}><Text style={s.section}>Sobre o acompanhamento</Text><Text style={s.body}>Os indicadores do VitaPoint são recursos de acompanhamento pessoal e não substituem avaliação de profissional de saúde.</Text></View><Pressable style={s.logout} onPress={signOut}><Text style={s.logoutText}>Sair da conta</Text></Pressable><Pressable style={s.back} onPress={()=>router.replace('/dashboard')}><Text style={s.backText}>Voltar ao início</Text></Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:24,paddingTop:62,paddingBottom:40},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F8FAFC'},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:'#5B5CE2'},title:{fontSize:30,fontWeight:'800',color:'#101828',marginTop:8,marginBottom:20},card:{backgroundColor:'#fff',borderRadius:20,padding:20,marginBottom:12,borderWidth:1,borderColor:'#EEF2F6'},name:{fontSize:20,fontWeight:'800',color:'#101828'},email:{fontSize:14,color:'#667085',marginTop:4},section:{fontSize:15,fontWeight:'800',color:'#101828',marginBottom:14},label:{fontSize:13,fontWeight:'700',color:'#344054',marginTop:8,marginBottom:6},input:{borderWidth:1,borderColor:'#E4E7EC',borderRadius:14,padding:14,fontSize:15,marginBottom:8,backgroundColor:'#fff'},value:{fontSize:13,color:'#667085',marginTop:8},body:{fontSize:14,lineHeight:21,color:'#667085'},primary:{backgroundColor:'#5B5CE2',padding:15,borderRadius:14,alignItems:'center',marginTop:16},primaryText:{color:'#fff',fontWeight:'800'},logout:{backgroundColor:'#fff',borderWidth:1,borderColor:'#FDA29B',padding:16,borderRadius:16,alignItems:'center',marginTop:8},logoutText:{color:'#B42318',fontWeight:'800'},back:{padding:16,alignItems:'center'},backText:{fontWeight:'700',color:'#475467'},error:{color:'#B42318',marginBottom:12}});