import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiRequest } from '../src/api';
import { getAccessToken } from '../src/auth';

type Trail={code:string;name:string;description:string;instruments:string[]};
type Recommended=Trail&{reason:string;clinical_disclaimer:string};
export default function Trails(){const [trails,setTrails]=useState<Trail[]>([]);const [recommended,setRecommended]=useState<Recommended|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
const load=useCallback(async()=>{setLoading(true);setError('');try{const token=await getAccessToken();const [all,rec]=await Promise.all([apiRequest<Trail[]>('/trails',{},token),apiRequest<Recommended>('/trails/recommended',{},token)]);setTrails(all);setRecommended(rec);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as trilhas.');}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>TRILHAS</Text><Text style={s.title}>Seu mapa de acompanhamento</Text><Text style={s.sub}>Jornadas progressivas baseadas no seu objetivo e no seu histórico.</Text>{loading&&<ActivityIndicator/>}{!!error&&<Text style={s.error}>{error}</Text>}{trails.map(t=>{const rec=t.code===recommended?.code;const demo=t.instruments.includes('DEMO_WELLBEING');return <Pressable key={t.code} style={[s.card,rec&&s.recommended]} onPress={()=>demo?router.push('/assessment-demo'):undefined}><View><Text style={s.cardTitle}>{t.name}</Text><Text style={s.desc}>{t.description}</Text><Text style={s.meta}>{t.instruments.length} indicadores planejados</Text></View><Text style={s.badge}>{rec?'RECOMENDADO':demo?'DISPONÍVEL':'EM PREPARAÇÃO'}</Text></Pressable>})}{recommended&&<View style={s.note}><Text style={s.noteTitle}>Por que esta trilha?</Text><Text style={s.desc}>{recommended.reason}</Text><Text style={s.disclaimer}>{recommended.clinical_disclaimer}</Text></View>}<Pressable style={s.back} onPress={()=>router.replace('/dashboard')}><Text style={s.backText}>Voltar ao início</Text></Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:24,paddingTop:62,paddingBottom:40},kicker:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:'#5B5CE2'},title:{fontSize:30,fontWeight:'800',color:'#101828',marginTop:8},sub:{fontSize:15,lineHeight:22,color:'#667085',marginTop:8,marginBottom:22},card:{backgroundColor:'#fff',borderRadius:20,padding:20,marginBottom:12,borderWidth:1,borderColor:'#EEF2F6'},recommended:{borderColor:'#A5B4FC'},cardTitle:{fontSize:17,fontWeight:'800',color:'#101828'},desc:{fontSize:14,lineHeight:20,color:'#667085',marginTop:6},meta:{fontSize:12,color:'#98A2B3',marginTop:10},badge:{alignSelf:'flex-start',marginTop:14,color:'#5B5CE2',fontWeight:'800',fontSize:11},note:{backgroundColor:'#EEF2FF',borderRadius:18,padding:18,marginTop:8},noteTitle:{fontWeight:'800',color:'#3730A3'},disclaimer:{fontSize:11,lineHeight:17,color:'#667085',marginTop:10},back:{padding:16,alignItems:'center'},backText:{fontWeight:'700',color:'#475467'},error:{color:'#B42318',marginBottom:12}});